apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  type: ClusterIP
  clusterIP: 10.99.11.11
  selector:
    app: influxdbPod
  ports:
      - port: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdbPod
        type: influxdbtype
    spec:
      containers: 
        - name: influxdbcontainer
          image: my-influxdb
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: "/var/lib/influxdb"
              name: influxdb
          livenessProbe:
            exec:
              command:
                - sh
                - /CheckSrvs.sh
            initialDelaySeconds: 60
            periodSeconds: 15
          imagePullPolicy: Never
      volumes:
        - name: influxdb
          hostPath:
            path: /mnt/influxdb
            type: Directory
  replicas: 1
  selector:
    matchLabels:
      app: influxdbPod
      type: influxdbtype