apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  clusterIP: 10.99.11.11
  ports:
  - name: influxdb
    port: 8086
  selector:
    app: NginxPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdbdeploy
spec:
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdbPod
        type: influxdb
    spec:
      containers: 
        - name: influxdbcontainer
          image: my-influxdb
          ports:
            - name: influxdb
              containerPort: 8086
          volumeMounts:
            - mountPath: "/var/lib/influxdb"
              name: influxdb
          livenessProbe:
            exec:
              command:
                - sh
                - /CheckSrvs.sh
            initialDelaySeconds: 60
            periodSeconds: 15
          imagePullPolicy: Never
      volumes:
        - name: influxdb
          hostPath:
            path: /mnt/influxdb
            type: Directory
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: influxdbPod
      type: influxdb