apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  clusterIP: 10.99.10.10
  selector:
    app: mysqlPod
  ports:
      - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysqlPod
        type: mysqltype
    spec:
      containers: 
        - name: mysqlcontainer
          image: my-mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql
          livenessProbe:
            exec:
              command:
                - sh
                - /CheckSrvs.sh
            initialDelaySeconds: 60
            periodSeconds: 15
          imagePullPolicy: Never
      volumes:
        - name: mysql
          hostPath:
            path: /mnt/mysql
            type: Directory
  replicas: 1
  selector:
    matchLabels:
      app: mysqlPod
      type: mysqltype