apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  clusterIP: 10.99.10.10
  selector:
    app: mysqlPod
  ports:
      - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysqlPod
        type: mysqltype
    spec:
      volumes:
        - name: db-pv
          persistentVolumeClaim:
            claimName: pv-claim 
      restartPolicy: Always
      containers: 
        - name: mysqlcontainer
          image: my-mysql
          ports:
            - containerPort: 3306
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: db-pv
  replicas: 1
  selector:
    matchLabels:
      app: mysqlPod
      type: mysqltype