apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: NginxPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: NginxPod
        type: nginx
    spec:
      containers: 
        - name: nginxcontainer
          image: my-nginx
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          imagePullPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: NginxPod
      type: nginx