apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: pma
    port: 5000
    targetPort: 5000
  selector:
    app: pmaPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: pmaPod
        type: pmatype
    spec:
      containers: 
        - name: phpmyadmincontainer
          image: my-phpmyadmin
          ports:
            - name: phpmyadmin
              containerPort: 5000
          imagePullPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: pmaPod
      type: pmatype