apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: port21
    port: 21
    targetPort: 21
  - name: port21000
    port: 21000
    targetPort: 21000
  - name: port21001
    port: 21001
    targetPort: 21001
  - name: port21002
    port: 21002
    targetPort: 21002
  - name: port21003
    port: 21003
    targetPort: 21003
  - name: port21004
    port: 21004
    targetPort: 21004
  - name: port21005
    port: 21005
    targetPort: 21005
  selector:
    app: ftpsPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftpsdeploy
spec:
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftpsPod
        type: ftps
    spec:
      containers: 
        - name: ftpscontainer
          image: my-ftps
          ports:
            - name: port21
              containerPort: 21
            - name: port21000
              containerPort: 21000
            - name: port21001
              containerPort: 21001
            - name: port21002
              containerPort: 21002
            - name: port21003
              containerPort: 21003
            - name: port21004
              containerPort: 21004
            - name: port21005
              containerPort: 21005
          livenessProbe:
            exec:
              command:
                - sh
                - /CheckSrvs.sh
            initialDelaySeconds: 60
            periodSeconds: 15
          imagePullPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: ftpsPod
      type: ftps
